import React, { createContext, useCallback, useContext, useState } from "react";

const translations = {
  en: {
    // Sidebar sections
    "nav.dashboard": "Dashboard",
    "nav.testing": "Testing",
    "nav.analysis": "Analysis",
    "nav.platform": "Platform",
    // Sidebar items
    "nav.testCases": "Test Cases",
    "nav.testPlans": "Test Plans",
    "nav.testRuns": "Test Runs",
    "nav.reports": "Reports",
    "nav.scheduling": "Scheduling",
    "nav.insights": "Insights",
    "nav.coverage": "Coverage",
    "nav.organizations": "Organizations",
    // Profile menu
    "profile.account": "Account",
    "profile.settings": "Settings",
    "profile.organizations": "Organizations",
    "profile.usageCredits": "Usage & Credits",
    "profile.appearance": "Appearance",
    "profile.language": "Language",
    "profile.help": "Help",
    "profile.signOut": "Sign out",
    "profile.organization": "Organization",
    // Appearance
    "appearance.light": "Light",
    "appearance.dark": "Dark",
    "appearance.system": "System",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your testing suite performance.",
    "dashboard.projects": "Projects",
    "dashboard.testCases": "Test Cases",
    "dashboard.successRate": "Success Rate",
    "dashboard.failures": "Failures",
    "dashboard.executionPlans": "execution plans",
    "dashboard.acrossAllProjects": "Across all projects",
    "dashboard.passed": "passed",
    "dashboard.failed": "failed",
    "dashboard.activeRuns": "active runs",
    "dashboard.openProjects": "Open Projects",
    "dashboard.teamAccess": "Team Access",
    "dashboard.executionTrends": "Execution Trends",
    "dashboard.lastRuns": "Last runs",
    "dashboard.success": "Success",
    "dashboard.running": "Running",
    "dashboard.orgVelocity": "Organization Velocity (Last 30h)",
    "dashboard.recentTestRuns": "Recent Test Runs",
    "dashboard.noTestRuns": "No test runs yet.",
    "dashboard.noTrendData": "No trend data yet.",
    // Scheduling
    "scheduling.title": "TNR Scheduling",
    "scheduling.subtitle": "Automate regression test runs. Configure parallel sessions for faster execution.",
    "scheduling.newSchedule": "New Schedule",
    "scheduling.editSchedule": "Edit Schedule",
    "scheduling.scheduleName": "Schedule Name",
    "scheduling.testPlan": "Test Plan",
    "scheduling.scheduleDate": "Schedule Date",
    "scheduling.time": "Time",
    "scheduling.timezone": "Timezone",
    "scheduling.parallelSessions": "Parallel Sessions",
    "scheduling.cancel": "Cancel",
    "scheduling.create": "Create Schedule",
    "scheduling.update": "Update Schedule",
    "scheduling.totalSchedules": "Total Schedules",
    "scheduling.active": "Active",
    "scheduling.paused": "Paused",
    "scheduling.totalRuns": "Total Runs",
    "scheduling.noSchedules": "No schedules yet",
    "scheduling.noSchedulesDesc": "Create a schedule to automate your regression test runs on a recurring basis.",
    "scheduling.createFirst": "Create First Schedule",
    "scheduling.loading": "Loading schedules...",
    "scheduling.selectPlan": "Select a test plan...",
    "scheduling.noPlanFound": "No test plans found. Create one with test cases first.",
    "scheduling.maxParallel": "Browser sessions running in parallel (max 4)",
    // Common
    "common.next": "Next",
    "common.last": "Last",
    "common.never": "Never",
    "common.runs": "runs",
    "common.overdue": "overdue",
    "common.delete": "Delete",
    "common.loading": "Loading...",
    "common.cancel": "Cancel",
    "common.create": "Create",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.clone": "Clone",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.actions": "Actions",
    "common.name": "Name",
    "common.description": "Description",
    "common.status": "Status",
    "common.title": "Title",
    "common.run": "Run",
    "common.open": "Open",
    "common.deleting": "Deleting...",
    "common.creating": "Creating...",
    "common.saving": "Saving...",
    "common.moving": "Moving...",
    "common.send": "Send",
    // Appearance (header)
    "appearance_light": "Light",
    "appearance_dark": "Dark",
    "appearance_system": "System",
    // Test Cases page
    "tc.tabs.repository": "Repository",
    "tc.tabs.sharedSteps": "Shared Steps",
    "tc.tabs.variables": "Variables",
    "tc.tabs.documentation": "Documentation",
    "tc.tabs.configuration": "Configuration",
    "tc.selectFolder": "Select a Folder",
    "tc.selectFolderDesc": "Choose a folder from the left panel to view and manage its test cases",
    "tc.aiAssistant": "AI Assistant",
    "tc.aiGenerator": "AI Test Case Generator",
    "tc.createTestCase": "Create Test Case",
    "tc.editTestCase": "Edit Test Case",
    "tc.deleteTestCase": "Delete Test Case",
    "tc.deleteSelected": "Delete Selected Test Cases",
    "tc.deleteFolder": "Delete Folder",
    "tc.importTestCases": "Import Test Cases",
    "tc.insertVariable": "Insert Variable",
    "tc.addVariable": "Add Variable",
    "tc.addSharedStep": "Add Shared Step",
    "tc.addEnvironment": "Add Environment",
    "tc.addStep": "Add Step",
    "tc.projectVariables": "Project Variables",
    "tc.projectDocumentation": "Project Documentation",
    "tc.projectDocDesc": "Fill all fields to provide exact business context for AI test generation.",
    "tc.projectSettings": "Project Settings",
    "tc.projectSettingsDesc": "Configure core metadata used by generation and execution contexts.",
    "tc.environments": "Environments",
    "tc.environmentsDesc": "Define target environments for execution and generation context.",
    "tc.uploadFiles": "Upload Reference Files",
    "tc.searchFolders": "Search folders...",
    "tc.searchTestCases": "Search test cases",
    "tc.noFolders": "No folders yet",
    "tc.noFoldersDesc": "Click the + button to create your first root folder.",
    "tc.noVariables": "No variables yet.",
    "tc.noSharedSteps": "No shared steps yet.",
    "tc.noFilesUploaded": "No files uploaded yet.",
    "tc.noEnvironments": "No environments configured yet.",
    "tc.noConversations": "No conversations yet.",
    "tc.newConversation": "Click \"+ New\" to start.",
    "tc.loadingFolders": "Loading folders...",
    "tc.folderName": "Folder Name",
    "tc.parentFolder": "Parent Folder",
    "tc.root": "Root",
    "tc.sortLastUpdated": "Sort: Last Updated",
    "tc.sortTitle": "Sort: Title",
    "tc.sortPriority": "Sort: Priority",
    "tc.priority": "Priority",
    "tc.type": "Type",
    "tc.automation": "Automation",
    "tc.tags": "Tags",
    "tc.steps": "Steps",
    "tc.action": "Action",
    "tc.expectedResult": "Expected result",
    "tc.importFromFile": "Import tests from file",
    "tc.createFolder": "Create folder",
    "tc.confirmMove": "Confirm Move",
    "tc.moveStepUp": "Move step up",
    "tc.moveStepDown": "Move step down",
    "tc.removeStep": "Remove step",
    "tc.previousTestCase": "Previous test case",
    "tc.nextTestCase": "Next test case",
    "tc.clearConversations": "Clear all conversations",
    "tc.deleteConversation": "Delete conversation",
    "tc.searchSharedSteps": "Search shared steps...",
    "tc.searchVariables": "Search variables",
    "tc.noMatchingVariable": "No matching variable",
    "tc.filesList": "Files List",
    "tc.supportedFormats": "Supported Formats",
    "tc.uploadImport": "Upload a file to import test cases...",
    "tc.projectName": "Project Name",
    "tc.baseUrl": "Base URL",
    "tc.saveSettings": "Save Settings",
    "tc.editFolder": "Edit Folder",
    "tc.saveChanges": "Save Changes",
    "tc.loadingProject": "Loading project...",
    "tc.project": "Project",
    "tc.noTestCasesMatch": "No test cases match your filters in this folder.",
    "tc.newGeneration": "New Generation",
    "tc.low": "Low",
    "tc.medium": "Medium",
    "tc.high": "High",
    "tc.critical": "Critical",
    "tc.functional": "Functional",
    "tc.regression": "Regression",
    "tc.smoke": "Smoke",
    "tc.integration": "Integration",
    "tc.other": "Other",
    "tc.notAutomated": "Not Automated",
    "tc.automated": "Automated",
    "tc.inProgress": "In Progress",
    "tc.active": "Active",
    "tc.draft": "Draft",
    "tc.inReview": "InReview",
    "tc.outdated": "Outdated",
    "tc.rejected": "Rejected",
    "tc.value": "Value",
    // Test Plans page
    "tp.title": "Test Plans",
    "tp.subtitle": "Group test cases and run them together",
    "tp.createPlan": "Create Plan",
    "tp.newPlan": "New Plan",
    "tp.project": "Project",
    "tp.environment": "Environment",
    "tp.noProjects": "No projects",
    "tp.noEnvironments": "No configured environments",
    "tp.addEnvHint": "Add environments in project configuration from Test Cases page.",
    "tp.searchPlans": "Search plans...",
    "tp.noPlans": "No plans found.",
    "tp.testCase": "test case",
    "tp.testCases": "test cases",
    "tp.passed": "passed",
    "tp.slotAvailability": "Slot availability",
    "tp.parallelSessions": "Parallel sessions",
    "tp.browserSession": "browser session",
    "tp.browserSessions": "browser sessions",
    "tp.runPlan": "Run",
    "tp.configureSessions": "Configure how many tests to run simultaneously.",
    "tp.openPage": "Open Page",
    "tp.justNow": "just now",
    "tp.staging": "staging",
    "tp.plan": "Plan",
    "tp.failedLoad": "Failed to load test plans",
    "tp.failedCreate": "Failed to create plan",
    "tp.failedRun": "Failed to run plan",
    "tp.failedDelete": "Failed to delete plan",
    "tp.noCredits": "No Credits",
    "tp.noCreditsDesc": "Your organization has no remaining credits.",
    "tp.concurrentLimit": "Your organization has reached its concurrent test limit.",
    // Test Runs page
    "tr.title": "Test Runs",
    "tr.subtitle": "View and manage test execution history",
    "tr.tabs.agentActions": "Agent Actions",
    "tr.tabs.agentResults": "Agent Results",
    "tr.tabs.testCase": "Test Case",
    "tr.tabs.video": "Video",
    "tr.tabs.console": "Console",
    "tr.tabs.network": "Network",
    "tr.rerunThis": "Re-run This",
    "tr.rerunAll": "Re-run All",
    "tr.rerunThisTitle": "Re-run this test",
    "tr.rerunAllTitle": "Re-run all tests",
    "tr.rerunThisDesc": "This will queue the selected test case again.",
    "tr.rerunAllDesc": "This will queue all test cases in this run.",
    "tr.parallelSessions": "Parallel sessions",
    "tr.parallelHint": "How many tests to run simultaneously (max 4)",
    "tr.pending": "Pending",
    "tr.completed": "Completed",
    "tr.passed": "Passed",
    "tr.failed": "Failed",
    "tr.running": "Running",
    "tr.queued": "Queued",
    "tr.aborted": "Aborted",
    "tr.error": "Error",
    "tr.allStatuses": "All statuses",
    "tr.testCaseResults": "Test case results",
    "tr.duration": "Duration",
    "tr.browser": "Browser",
    "tr.total": "total",
    "tr.skipped": "skipped",
    "tr.noProjects": "No projects",
    "tr.noRuns": "No runs found.",
    "tr.agentRunning": "Agent is still running...",
    "tr.noAgentResults": "No agent results available.",
    "tr.stepPassed": "AI noted this step passed successfully.",
    "tr.aiNote": "AI Note",
    "tr.noSteps": "No test case steps defined.",
    "tr.expectedResult": "Expected Result",
    "tr.videoNotAvailable": "Video not available yet.",
    "tr.consoleNotAvailable": "Console logs not available yet.",
    "tr.networkNotAvailable": "Network logs not available yet.",
    "tr.method": "Method",
    "tr.url": "URL",
    "tr.openPage": "Open Page",
    "tr.imageUnavailable": "Image unavailable",
  },
  fr: {
    "nav.dashboard": "Tableau de bord",
    "nav.testing": "Tests",
    "nav.analysis": "Analyse",
    "nav.platform": "Plateforme",
    "nav.testCases": "Cas de test",
    "nav.testPlans": "Plans de test",
    "nav.testRuns": "Exécutions",
    "nav.reports": "Rapports",
    "nav.scheduling": "Planification",
    "nav.insights": "Insights",
    "nav.coverage": "Couverture",
    "nav.organizations": "Organisations",
    "profile.account": "Compte",
    "profile.settings": "Paramètres",
    "profile.organizations": "Organisations",
    "profile.usageCredits": "Utilisation & Crédits",
    "profile.appearance": "Apparence",
    "profile.language": "Langue",
    "profile.help": "Aide",
    "profile.signOut": "Déconnexion",
    "profile.organization": "Organisation",
    "appearance.light": "Clair",
    "appearance.dark": "Sombre",
    "appearance.system": "Système",
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Vue d'ensemble des performances de vos tests.",
    "dashboard.projects": "Projets",
    "dashboard.testCases": "Cas de test",
    "dashboard.successRate": "Taux de réussite",
    "dashboard.failures": "Échecs",
    "dashboard.executionPlans": "plans d'exécution",
    "dashboard.acrossAllProjects": "Tous les projets",
    "dashboard.passed": "réussis",
    "dashboard.failed": "échoués",
    "dashboard.activeRuns": "exécutions actives",
    "dashboard.openProjects": "Ouvrir les projets",
    "dashboard.teamAccess": "Accès équipe",
    "dashboard.executionTrends": "Tendances d'exécution",
    "dashboard.lastRuns": "Dernières exécutions",
    "dashboard.success": "Réussite",
    "dashboard.running": "En cours",
    "dashboard.orgVelocity": "Vélocité de l'organisation (30 dernières h)",
    "dashboard.recentTestRuns": "Exécutions récentes",
    "dashboard.noTestRuns": "Aucune exécution pour le moment.",
    "dashboard.noTrendData": "Aucune donnée de tendance.",
    "scheduling.title": "Planification TNR",
    "scheduling.subtitle": "Automatisez les tests de régression. Configurez les sessions parallèles.",
    "scheduling.newSchedule": "Nouvelle planification",
    "scheduling.editSchedule": "Modifier la planification",
    "scheduling.scheduleName": "Nom de la planification",
    "scheduling.testPlan": "Plan de test",
    "scheduling.scheduleDate": "Date de planification",
    "scheduling.time": "Heure",
    "scheduling.timezone": "Fuseau horaire",
    "scheduling.parallelSessions": "Sessions parallèles",
    "scheduling.cancel": "Annuler",
    "scheduling.create": "Créer la planification",
    "scheduling.update": "Mettre à jour",
    "scheduling.totalSchedules": "Total planifications",
    "scheduling.active": "Actives",
    "scheduling.paused": "En pause",
    "scheduling.totalRuns": "Total exécutions",
    "scheduling.noSchedules": "Aucune planification",
    "scheduling.noSchedulesDesc": "Créez une planification pour automatiser vos tests de régression.",
    "scheduling.createFirst": "Créer la première planification",
    "scheduling.loading": "Chargement des planifications...",
    "scheduling.selectPlan": "Sélectionner un plan de test...",
    "scheduling.noPlanFound": "Aucun plan de test trouvé. Créez-en un d'abord.",
    "scheduling.maxParallel": "Sessions navigateur en parallèle (max 4)",
    "common.next": "Prochain",
    "common.last": "Dernier",
    "common.never": "Jamais",
    "common.runs": "exécutions",
    "common.overdue": "en retard",
    "common.delete": "Supprimer",
    "common.loading": "Chargement...",
    "common.cancel": "Annuler",
    "common.create": "Créer",
    "common.save": "Enregistrer",
    "common.edit": "Modifier",
    "common.clone": "Cloner",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.actions": "Actions",
    "common.name": "Nom",
    "common.description": "Description",
    "common.status": "Statut",
    "common.title": "Titre",
    "common.run": "Exécuter",
    "common.open": "Ouvrir",
    "common.deleting": "Suppression...",
    "common.creating": "Création...",
    "common.saving": "Enregistrement...",
    "common.moving": "Déplacement...",
    "common.send": "Envoyer",
    "appearance_light": "Clair",
    "appearance_dark": "Sombre",
    "appearance_system": "Système",
    // Test Cases page
    "tc.tabs.repository": "Dépôt",
    "tc.tabs.sharedSteps": "Étapes partagées",
    "tc.tabs.variables": "Variables",
    "tc.tabs.documentation": "Documentation",
    "tc.tabs.configuration": "Configuration",
    "tc.selectFolder": "Sélectionner un dossier",
    "tc.selectFolderDesc": "Choisissez un dossier dans le panneau de gauche pour voir et gérer ses cas de test",
    "tc.aiAssistant": "Assistant IA",
    "tc.aiGenerator": "Générateur de cas de test IA",
    "tc.createTestCase": "Créer un cas de test",
    "tc.editTestCase": "Modifier le cas de test",
    "tc.deleteTestCase": "Supprimer le cas de test",
    "tc.deleteSelected": "Supprimer les cas sélectionnés",
    "tc.deleteFolder": "Supprimer le dossier",
    "tc.importTestCases": "Importer des cas de test",
    "tc.insertVariable": "Insérer une variable",
    "tc.addVariable": "Ajouter une variable",
    "tc.addSharedStep": "Ajouter une étape partagée",
    "tc.addEnvironment": "Ajouter un environnement",
    "tc.addStep": "Ajouter une étape",
    "tc.projectVariables": "Variables du projet",
    "tc.projectDocumentation": "Documentation du projet",
    "tc.projectDocDesc": "Remplissez tous les champs pour fournir le contexte métier exact pour la génération IA.",
    "tc.projectSettings": "Paramètres du projet",
    "tc.projectSettingsDesc": "Configurez les métadonnées de base pour les contextes de génération et d'exécution.",
    "tc.environments": "Environnements",
    "tc.environmentsDesc": "Définissez les environnements cibles pour l'exécution et la génération.",
    "tc.uploadFiles": "Télécharger des fichiers de référence",
    "tc.searchFolders": "Rechercher des dossiers...",
    "tc.searchTestCases": "Rechercher des cas de test",
    "tc.noFolders": "Aucun dossier",
    "tc.noFoldersDesc": "Cliquez sur le bouton + pour créer votre premier dossier racine.",
    "tc.noVariables": "Aucune variable.",
    "tc.noSharedSteps": "Aucune étape partagée.",
    "tc.noFilesUploaded": "Aucun fichier téléchargé.",
    "tc.noEnvironments": "Aucun environnement configuré.",
    "tc.noConversations": "Aucune conversation.",
    "tc.newConversation": "Cliquez sur \"+ Nouveau\" pour commencer.",
    "tc.loadingFolders": "Chargement des dossiers...",
    "tc.folderName": "Nom du dossier",
    "tc.parentFolder": "Dossier parent",
    "tc.root": "Racine",
    "tc.sortLastUpdated": "Tri : Dernière mise à jour",
    "tc.sortTitle": "Tri : Titre",
    "tc.sortPriority": "Tri : Priorité",
    "tc.priority": "Priorité",
    "tc.type": "Type",
    "tc.automation": "Automatisation",
    "tc.tags": "Tags",
    "tc.steps": "Étapes",
    "tc.action": "Action",
    "tc.expectedResult": "Résultat attendu",
    "tc.importFromFile": "Importer des tests depuis un fichier",
    "tc.createFolder": "Créer un dossier",
    "tc.confirmMove": "Confirmer le déplacement",
    "tc.moveStepUp": "Monter l'étape",
    "tc.moveStepDown": "Descendre l'étape",
    "tc.removeStep": "Supprimer l'étape",
    "tc.previousTestCase": "Cas de test précédent",
    "tc.nextTestCase": "Cas de test suivant",
    "tc.clearConversations": "Effacer toutes les conversations",
    "tc.deleteConversation": "Supprimer la conversation",
    "tc.searchSharedSteps": "Rechercher des étapes partagées...",
    "tc.searchVariables": "Rechercher des variables",
    "tc.noMatchingVariable": "Aucune variable correspondante",
    "tc.filesList": "Liste des fichiers",
    "tc.supportedFormats": "Formats supportés",
    "tc.uploadImport": "Téléchargez un fichier pour importer des cas de test...",
    "tc.projectName": "Nom du projet",
    "tc.baseUrl": "URL de base",
    "tc.saveSettings": "Enregistrer les paramètres",
    "tc.editFolder": "Modifier le dossier",
    "tc.saveChanges": "Enregistrer",
    "tc.loadingProject": "Chargement du projet...",
    "tc.project": "Projet",
    "tc.noTestCasesMatch": "Aucun cas de test ne correspond à vos filtres dans ce dossier.",
    "tc.newGeneration": "Nouvelle génération",
    "tc.low": "Basse",
    "tc.medium": "Moyenne",
    "tc.high": "Haute",
    "tc.critical": "Critique",
    "tc.functional": "Fonctionnel",
    "tc.regression": "Régression",
    "tc.smoke": "Smoke",
    "tc.integration": "Intégration",
    "tc.other": "Autre",
    "tc.notAutomated": "Non automatisé",
    "tc.automated": "Automatisé",
    "tc.inProgress": "En cours",
    "tc.active": "Actif",
    "tc.draft": "Brouillon",
    "tc.inReview": "En revue",
    "tc.outdated": "Obsolète",
    "tc.rejected": "Rejeté",
    "tc.value": "Valeur",
    // Test Plans page
    "tp.title": "Plans de test",
    "tp.subtitle": "Regroupez les cas de test et exécutez-les ensemble",
    "tp.createPlan": "Créer un plan",
    "tp.newPlan": "Nouveau plan",
    "tp.project": "Projet",
    "tp.environment": "Environnement",
    "tp.noProjects": "Aucun projet",
    "tp.noEnvironments": "Aucun environnement configuré",
    "tp.addEnvHint": "Ajoutez des environnements dans la configuration du projet depuis la page Cas de test.",
    "tp.searchPlans": "Rechercher des plans...",
    "tp.noPlans": "Aucun plan trouvé.",
    "tp.testCase": "cas de test",
    "tp.testCases": "cas de test",
    "tp.passed": "réussis",
    "tp.slotAvailability": "Disponibilité des slots",
    "tp.parallelSessions": "Sessions parallèles",
    "tp.browserSession": "session navigateur",
    "tp.browserSessions": "sessions navigateur",
    "tp.runPlan": "Exécuter",
    "tp.configureSessions": "Configurez le nombre de tests à exécuter simultanément.",
    "tp.openPage": "Ouvrir la page",
    "tp.justNow": "à l'instant",
    "tp.staging": "staging",
    "tp.plan": "Plan",
    "tp.failedLoad": "Échec du chargement des plans de test",
    "tp.failedCreate": "Échec de la création du plan",
    "tp.failedRun": "Échec de l'exécution du plan",
    "tp.failedDelete": "Échec de la suppression du plan",
    "tp.noCredits": "Aucun crédit",
    "tp.noCreditsDesc": "Votre organisation n'a plus de crédits.",
    "tp.concurrentLimit": "Votre organisation a atteint sa limite de tests simultanés.",
    // Test Runs page
    "tr.title": "Exécutions de tests",
    "tr.subtitle": "Consultez et gérez l'historique d'exécution des tests",
    "tr.tabs.agentActions": "Actions de l'agent",
    "tr.tabs.agentResults": "Résultats de l'agent",
    "tr.tabs.testCase": "Cas de test",
    "tr.tabs.video": "Vidéo",
    "tr.tabs.console": "Console",
    "tr.tabs.network": "Réseau",
    "tr.rerunThis": "Relancer ce test",
    "tr.rerunAll": "Tout relancer",
    "tr.rerunThisTitle": "Relancer ce test",
    "tr.rerunAllTitle": "Relancer tous les tests",
    "tr.rerunThisDesc": "Ce cas de test sera remis en file d'attente.",
    "tr.rerunAllDesc": "Tous les cas de test de cette exécution seront remis en file d'attente.",
    "tr.parallelSessions": "Sessions parallèles",
    "tr.parallelHint": "Nombre de tests à exécuter simultanément (max 4)",
    "tr.pending": "En attente",
    "tr.completed": "Terminé",
    "tr.passed": "Réussi",
    "tr.failed": "Échoué",
    "tr.running": "En cours",
    "tr.queued": "En file",
    "tr.aborted": "Annulé",
    "tr.error": "Erreur",
    "tr.allStatuses": "Tous les statuts",
    "tr.testCaseResults": "Résultats des cas de test",
    "tr.duration": "Durée",
    "tr.browser": "Navigateur",
    "tr.total": "total",
    "tr.skipped": "ignorés",
    "tr.noProjects": "Aucun projet",
    "tr.noRuns": "Aucune exécution trouvée.",
    "tr.agentRunning": "L'agent est en cours d'exécution...",
    "tr.noAgentResults": "Aucun résultat d'agent disponible.",
    "tr.stepPassed": "L'IA a noté que cette étape a réussi.",
    "tr.aiNote": "Note IA",
    "tr.noSteps": "Aucune étape de cas de test définie.",
    "tr.expectedResult": "Résultat attendu",
    "tr.videoNotAvailable": "Vidéo pas encore disponible.",
    "tr.consoleNotAvailable": "Logs console pas encore disponibles.",
    "tr.networkNotAvailable": "Logs réseau pas encore disponibles.",
    "tr.method": "Méthode",
    "tr.url": "URL",
    "tr.openPage": "Ouvrir la page",
    "tr.imageUnavailable": "Image indisponible",
  },
  es: {
    "nav.dashboard": "Panel",
    "nav.testing": "Pruebas",
    "nav.analysis": "Análisis",
    "nav.platform": "Plataforma",
    "nav.testCases": "Casos de prueba",
    "nav.testPlans": "Planes de prueba",
    "nav.testRuns": "Ejecuciones",
    "nav.reports": "Informes",
    "nav.scheduling": "Programación",
    "nav.insights": "Perspectivas",
    "nav.coverage": "Cobertura",
    "nav.organizations": "Organizaciones",
    "profile.account": "Cuenta",
    "profile.settings": "Configuración",
    "profile.organizations": "Organizaciones",
    "profile.usageCredits": "Uso y Créditos",
    "profile.appearance": "Apariencia",
    "profile.language": "Idioma",
    "profile.help": "Ayuda",
    "profile.signOut": "Cerrar sesión",
    "profile.organization": "Organización",
    "appearance.light": "Claro",
    "appearance.dark": "Oscuro",
    "appearance.system": "Sistema",
    "dashboard.title": "Panel",
    "dashboard.subtitle": "Resumen del rendimiento de sus pruebas.",
    "dashboard.projects": "Proyectos",
    "dashboard.testCases": "Casos de prueba",
    "dashboard.successRate": "Tasa de éxito",
    "dashboard.failures": "Fallos",
    "dashboard.executionPlans": "planes de ejecución",
    "dashboard.acrossAllProjects": "Todos los proyectos",
    "dashboard.passed": "pasados",
    "dashboard.failed": "fallados",
    "dashboard.activeRuns": "ejecuciones activas",
    "dashboard.openProjects": "Abrir proyectos",
    "dashboard.teamAccess": "Acceso del equipo",
    "dashboard.executionTrends": "Tendencias de ejecución",
    "dashboard.lastRuns": "Últimas ejecuciones",
    "dashboard.success": "Éxito",
    "dashboard.running": "En curso",
    "dashboard.orgVelocity": "Velocidad de la organización (últimas 30h)",
    "dashboard.recentTestRuns": "Ejecuciones recientes",
    "dashboard.noTestRuns": "Sin ejecuciones aún.",
    "dashboard.noTrendData": "Sin datos de tendencia.",
    "scheduling.title": "Programación TNR",
    "scheduling.subtitle": "Automatice las pruebas de regresión. Configure sesiones paralelas.",
    "scheduling.newSchedule": "Nueva programación",
    "scheduling.editSchedule": "Editar programación",
    "scheduling.scheduleName": "Nombre de la programación",
    "scheduling.testPlan": "Plan de prueba",
    "scheduling.scheduleDate": "Fecha de programación",
    "scheduling.time": "Hora",
    "scheduling.timezone": "Zona horaria",
    "scheduling.parallelSessions": "Sesiones paralelas",
    "scheduling.cancel": "Cancelar",
    "scheduling.create": "Crear programación",
    "scheduling.update": "Actualizar",
    "scheduling.totalSchedules": "Total programaciones",
    "scheduling.active": "Activas",
    "scheduling.paused": "En pausa",
    "scheduling.totalRuns": "Total ejecuciones",
    "scheduling.noSchedules": "Sin programaciones",
    "scheduling.noSchedulesDesc": "Cree una programación para automatizar sus pruebas de regresión.",
    "scheduling.createFirst": "Crear primera programación",
    "scheduling.loading": "Cargando programaciones...",
    "scheduling.selectPlan": "Seleccionar un plan de prueba...",
    "scheduling.noPlanFound": "No se encontraron planes de prueba. Cree uno primero.",
    "scheduling.maxParallel": "Sesiones de navegador en paralelo (máx 4)",
    "common.next": "Siguiente",
    "common.last": "Último",
    "common.never": "Nunca",
    "common.runs": "ejecuciones",
    "common.overdue": "vencido",
    "common.delete": "Eliminar",
    "common.loading": "Cargando...",
    "common.cancel": "Cancelar",
    "common.create": "Crear",
    "common.save": "Guardar",
    "common.edit": "Editar",
    "common.clone": "Clonar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.actions": "Acciones",
    "common.name": "Nombre",
    "common.description": "Descripción",
    "common.status": "Estado",
    "common.title": "Título",
    "common.run": "Ejecutar",
    "common.open": "Abrir",
    "common.deleting": "Eliminando...",
    "common.creating": "Creando...",
    "common.saving": "Guardando...",
    "common.moving": "Moviendo...",
    "common.send": "Enviar",
    "appearance_light": "Claro",
    "appearance_dark": "Oscuro",
    "appearance_system": "Sistema",
    // Test Cases page
    "tc.tabs.repository": "Repositorio",
    "tc.tabs.sharedSteps": "Pasos compartidos",
    "tc.tabs.variables": "Variables",
    "tc.tabs.documentation": "Documentación",
    "tc.tabs.configuration": "Configuración",
    "tc.selectFolder": "Seleccionar una carpeta",
    "tc.selectFolderDesc": "Elija una carpeta del panel izquierdo para ver y gestionar sus casos de prueba",
    "tc.aiAssistant": "Asistente IA",
    "tc.aiGenerator": "Generador de casos de prueba IA",
    "tc.createTestCase": "Crear caso de prueba",
    "tc.editTestCase": "Editar caso de prueba",
    "tc.deleteTestCase": "Eliminar caso de prueba",
    "tc.deleteSelected": "Eliminar casos seleccionados",
    "tc.deleteFolder": "Eliminar carpeta",
    "tc.importTestCases": "Importar casos de prueba",
    "tc.insertVariable": "Insertar variable",
    "tc.addVariable": "Agregar variable",
    "tc.addSharedStep": "Agregar paso compartido",
    "tc.addEnvironment": "Agregar entorno",
    "tc.addStep": "Agregar paso",
    "tc.projectVariables": "Variables del proyecto",
    "tc.projectDocumentation": "Documentación del proyecto",
    "tc.projectDocDesc": "Complete todos los campos para proporcionar el contexto empresarial exacto para la generación IA.",
    "tc.projectSettings": "Configuración del proyecto",
    "tc.projectSettingsDesc": "Configure los metadatos básicos para los contextos de generación y ejecución.",
    "tc.environments": "Entornos",
    "tc.environmentsDesc": "Defina los entornos objetivo para la ejecución y generación.",
    "tc.uploadFiles": "Subir archivos de referencia",
    "tc.searchFolders": "Buscar carpetas...",
    "tc.searchTestCases": "Buscar casos de prueba",
    "tc.noFolders": "Sin carpetas",
    "tc.noFoldersDesc": "Haga clic en el botón + para crear su primera carpeta raíz.",
    "tc.noVariables": "Sin variables.",
    "tc.noSharedSteps": "Sin pasos compartidos.",
    "tc.noFilesUploaded": "Sin archivos subidos.",
    "tc.noEnvironments": "Sin entornos configurados.",
    "tc.noConversations": "Sin conversaciones.",
    "tc.newConversation": "Haga clic en \"+ Nuevo\" para comenzar.",
    "tc.loadingFolders": "Cargando carpetas...",
    "tc.folderName": "Nombre de la carpeta",
    "tc.parentFolder": "Carpeta padre",
    "tc.root": "Raíz",
    "tc.sortLastUpdated": "Orden: Última actualización",
    "tc.sortTitle": "Orden: Título",
    "tc.sortPriority": "Orden: Prioridad",
    "tc.priority": "Prioridad",
    "tc.type": "Tipo",
    "tc.automation": "Automatización",
    "tc.tags": "Etiquetas",
    "tc.steps": "Pasos",
    "tc.action": "Acción",
    "tc.expectedResult": "Resultado esperado",
    "tc.importFromFile": "Importar pruebas desde archivo",
    "tc.createFolder": "Crear carpeta",
    "tc.confirmMove": "Confirmar movimiento",
    "tc.moveStepUp": "Mover paso arriba",
    "tc.moveStepDown": "Mover paso abajo",
    "tc.removeStep": "Eliminar paso",
    "tc.previousTestCase": "Caso de prueba anterior",
    "tc.nextTestCase": "Siguiente caso de prueba",
    "tc.clearConversations": "Borrar todas las conversaciones",
    "tc.deleteConversation": "Eliminar conversación",
    "tc.searchSharedSteps": "Buscar pasos compartidos...",
    "tc.searchVariables": "Buscar variables",
    "tc.noMatchingVariable": "Sin variable coincidente",
    "tc.filesList": "Lista de archivos",
    "tc.supportedFormats": "Formatos soportados",
    "tc.uploadImport": "Suba un archivo para importar casos de prueba...",
    "tc.projectName": "Nombre del proyecto",
    "tc.baseUrl": "URL base",
    "tc.saveSettings": "Guardar configuración",
    "tc.editFolder": "Editar carpeta",
    "tc.saveChanges": "Guardar cambios",
    "tc.loadingProject": "Cargando proyecto...",
    "tc.project": "Proyecto",
    "tc.noTestCasesMatch": "Ningún caso de prueba coincide con tus filtros en esta carpeta.",
    "tc.newGeneration": "Nueva generación",
    "tc.low": "Baja",
    "tc.medium": "Media",
    "tc.high": "Alta",
    "tc.critical": "Crítica",
    "tc.functional": "Funcional",
    "tc.regression": "Regresión",
    "tc.smoke": "Smoke",
    "tc.integration": "Integración",
    "tc.other": "Otro",
    "tc.notAutomated": "No automatizado",
    "tc.automated": "Automatizado",
    "tc.inProgress": "En progreso",
    "tc.active": "Activo",
    "tc.draft": "Borrador",
    "tc.inReview": "En revisión",
    "tc.outdated": "Obsoleto",
    "tc.rejected": "Rechazado",
    "tc.value": "Valor",
    // Test Plans page
    "tp.title": "Planes de prueba",
    "tp.subtitle": "Agrupe los casos de prueba y ejecútelos juntos",
    "tp.createPlan": "Crear plan",
    "tp.newPlan": "Nuevo plan",
    "tp.project": "Proyecto",
    "tp.environment": "Entorno",
    "tp.noProjects": "Sin proyectos",
    "tp.noEnvironments": "Sin entornos configurados",
    "tp.addEnvHint": "Agregue entornos en la configuración del proyecto desde la página Casos de prueba.",
    "tp.searchPlans": "Buscar planes...",
    "tp.noPlans": "No se encontraron planes.",
    "tp.testCase": "caso de prueba",
    "tp.testCases": "casos de prueba",
    "tp.passed": "pasados",
    "tp.slotAvailability": "Disponibilidad de slots",
    "tp.parallelSessions": "Sesiones paralelas",
    "tp.browserSession": "sesión de navegador",
    "tp.browserSessions": "sesiones de navegador",
    "tp.runPlan": "Ejecutar",
    "tp.configureSessions": "Configure cuántas pruebas ejecutar simultáneamente.",
    "tp.openPage": "Abrir página",
    "tp.justNow": "ahora mismo",
    "tp.staging": "staging",
    "tp.plan": "Plan",
    "tp.failedLoad": "Error al cargar los planes de prueba",
    "tp.failedCreate": "Error al crear el plan",
    "tp.failedRun": "Error al ejecutar el plan",
    "tp.failedDelete": "Error al eliminar el plan",
    "tp.noCredits": "Sin créditos",
    "tp.noCreditsDesc": "Su organización no tiene créditos restantes.",
    "tp.concurrentLimit": "Su organización ha alcanzado su límite de pruebas simultáneas.",
    // Test Runs page
    "tr.title": "Ejecuciones de pruebas",
    "tr.subtitle": "Vea y gestione el historial de ejecución de pruebas",
    "tr.tabs.agentActions": "Acciones del agente",
    "tr.tabs.agentResults": "Resultados del agente",
    "tr.tabs.testCase": "Caso de prueba",
    "tr.tabs.video": "Video",
    "tr.tabs.console": "Consola",
    "tr.tabs.network": "Red",
    "tr.rerunThis": "Reejecutar este",
    "tr.rerunAll": "Reejecutar todo",
    "tr.rerunThisTitle": "Reejecutar esta prueba",
    "tr.rerunAllTitle": "Reejecutar todas las pruebas",
    "tr.rerunThisDesc": "Este caso de prueba se pondrá en cola de nuevo.",
    "tr.rerunAllDesc": "Todos los casos de prueba de esta ejecución se pondrán en cola.",
    "tr.parallelSessions": "Sesiones paralelas",
    "tr.parallelHint": "Cuántas pruebas ejecutar simultáneamente (máx 4)",
    "tr.pending": "Pendiente",
    "tr.completed": "Completado",
    "tr.passed": "Pasado",
    "tr.failed": "Fallado",
    "tr.running": "En ejecución",
    "tr.queued": "En cola",
    "tr.aborted": "Abortado",
    "tr.error": "Error",
    "tr.allStatuses": "Todos los estados",
    "tr.testCaseResults": "Resultados de casos de prueba",
    "tr.duration": "Duración",
    "tr.browser": "Navegador",
    "tr.total": "total",
    "tr.skipped": "omitidos",
    "tr.noProjects": "Sin proyectos",
    "tr.noRuns": "No se encontraron ejecuciones.",
    "tr.agentRunning": "El agente sigue en ejecución...",
    "tr.noAgentResults": "Sin resultados de agente disponibles.",
    "tr.stepPassed": "La IA notó que este paso se completó con éxito.",
    "tr.aiNote": "Nota IA",
    "tr.noSteps": "Sin pasos de caso de prueba definidos.",
    "tr.expectedResult": "Resultado esperado",
    "tr.videoNotAvailable": "Video no disponible aún.",
    "tr.consoleNotAvailable": "Logs de consola no disponibles aún.",
    "tr.networkNotAvailable": "Logs de red no disponibles aún.",
    "tr.method": "Método",
    "tr.url": "URL",
    "tr.openPage": "Abrir página",
    "tr.imageUnavailable": "Imagen no disponible",
  },
};

const LanguageContext = createContext(undefined);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try { return localStorage.getItem("app_language") || "en"; } catch { return "en"; }
  });

  const setLang = useCallback((newLang) => {
    setLangState(newLang);
    try { localStorage.setItem("app_language", newLang); } catch {}
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.en?.[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return { lang: "en", setLang: () => {}, t: (k) => k };
  }
  return context;
}
