import React, { createContext, useCallback, useContext, useState } from "react";

const translations = {
  en: {
    // Sidebar sections
    "nav.dashboard": "Dashboard",
    "nav.testing": "Testing",
    "nav.analysis": "Analysis",
    "nav.platform": "Platform",
    // Sidebar items
    "nav.testCases": "Test Cases",
    "nav.testPlans": "Test Plans",
    "nav.testRuns": "Test Runs",
    "nav.reports": "Reports",
    "nav.scheduling": "Scheduling",
    "nav.insights": "Insights",
    "nav.coverage": "Coverage",
    "nav.organizations": "Organizations",
    // Profile menu
    "profile.account": "Account",
    "profile.settings": "Settings",
    "profile.organizations": "Organizations",
    "profile.usageCredits": "Usage & Credits",
    "profile.appearance": "Appearance",
    "profile.language": "Language",
    "profile.help": "Help",
    "profile.signOut": "Sign out",
    "profile.organization": "Organization",
    // Appearance
    "appearance.light": "Light",
    "appearance.dark": "Dark",
    "appearance.system": "System",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your testing suite performance.",
    "dashboard.projects": "Projects",
    "dashboard.testCases": "Test Cases",
    "dashboard.successRate": "Success Rate",
    "dashboard.failures": "Failures",
    "dashboard.executionPlans": "execution plans",
    "dashboard.acrossAllProjects": "Across all projects",
    "dashboard.passed": "passed",
    "dashboard.failed": "failed",
    "dashboard.activeRuns": "active runs",
    "dashboard.openProjects": "Open Projects",
    "dashboard.teamAccess": "Team Access",
    "dashboard.executionTrends": "Execution Trends",
    "dashboard.lastRuns": "Last runs",
    "dashboard.success": "Success",
    "dashboard.running": "Running",
    "dashboard.orgVelocity": "Organization Velocity (Last 30h)",
    "dashboard.recentTestRuns": "Recent Test Runs",
    "dashboard.noTestRuns": "No test runs yet.",
    "dashboard.noTrendData": "No trend data yet.",
    // Scheduling
    "scheduling.title": "TNR Scheduling",
    "scheduling.subtitle": "Automate regression test runs. Configure parallel sessions for faster execution.",
    "scheduling.newSchedule": "New Schedule",
    "scheduling.editSchedule": "Edit Schedule",
    "scheduling.scheduleName": "Schedule Name",
    "scheduling.testPlan": "Test Plan",
    "scheduling.scheduleDate": "Schedule Date",
    "scheduling.time": "Time",
    "scheduling.timezone": "Timezone",
    "scheduling.parallelSessions": "Parallel Sessions",
    "scheduling.cancel": "Cancel",
    "scheduling.create": "Create Schedule",
    "scheduling.update": "Update Schedule",
    "scheduling.totalSchedules": "Total Schedules",
    "scheduling.active": "Active",
    "scheduling.paused": "Paused",
    "scheduling.totalRuns": "Total Runs",
    "scheduling.noSchedules": "No schedules yet",
    "scheduling.noSchedulesDesc": "Create a schedule to automate your regression test runs on a recurring basis.",
    "scheduling.createFirst": "Create First Schedule",
    "scheduling.loading": "Loading schedules...",
    "scheduling.selectPlan": "Select a test plan...",
    "scheduling.noPlanFound": "No test plans found. Create one with test cases first.",
    "scheduling.maxParallel": "Browser sessions running in parallel (max 4)",
    // Common
    "common.next": "Next",
    "common.last": "Last",
    "common.never": "Never",
    "common.runs": "runs",
    "common.overdue": "overdue",
    "common.delete": "Delete",
    "common.loading": "Loading...",
  },
  fr: {
    "nav.dashboard": "Tableau de bord",
    "nav.testing": "Tests",
    "nav.analysis": "Analyse",
    "nav.platform": "Plateforme",
    "nav.testCases": "Cas de test",
    "nav.testPlans": "Plans de test",
    "nav.testRuns": "Exécutions",
    "nav.reports": "Rapports",
    "nav.scheduling": "Planification",
    "nav.insights": "Insights",
    "nav.coverage": "Couverture",
    "nav.organizations": "Organisations",
    "profile.account": "Compte",
    "profile.settings": "Paramètres",
    "profile.organizations": "Organisations",
    "profile.usageCredits": "Utilisation & Crédits",
    "profile.appearance": "Apparence",
    "profile.language": "Langue",
    "profile.help": "Aide",
    "profile.signOut": "Déconnexion",
    "profile.organization": "Organisation",
    "appearance.light": "Clair",
    "appearance.dark": "Sombre",
    "appearance.system": "Système",
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Vue d'ensemble des performances de vos tests.",
    "dashboard.projects": "Projets",
    "dashboard.testCases": "Cas de test",
    "dashboard.successRate": "Taux de réussite",
    "dashboard.failures": "Échecs",
    "dashboard.executionPlans": "plans d'exécution",
    "dashboard.acrossAllProjects": "Tous les projets",
    "dashboard.passed": "réussis",
    "dashboard.failed": "échoués",
    "dashboard.activeRuns": "exécutions actives",
    "dashboard.openProjects": "Ouvrir les projets",
    "dashboard.teamAccess": "Accès équipe",
    "dashboard.executionTrends": "Tendances d'exécution",
    "dashboard.lastRuns": "Dernières exécutions",
    "dashboard.success": "Réussite",
    "dashboard.running": "En cours",
    "dashboard.orgVelocity": "Vélocité de l'organisation (30 dernières h)",
    "dashboard.recentTestRuns": "Exécutions récentes",
    "dashboard.noTestRuns": "Aucune exécution pour le moment.",
    "dashboard.noTrendData": "Aucune donnée de tendance.",
    "scheduling.title": "Planification TNR",
    "scheduling.subtitle": "Automatisez les tests de régression. Configurez les sessions parallèles.",
    "scheduling.newSchedule": "Nouvelle planification",
    "scheduling.editSchedule": "Modifier la planification",
    "scheduling.scheduleName": "Nom de la planification",
    "scheduling.testPlan": "Plan de test",
    "scheduling.scheduleDate": "Date de planification",
    "scheduling.time": "Heure",
    "scheduling.timezone": "Fuseau horaire",
    "scheduling.parallelSessions": "Sessions parallèles",
    "scheduling.cancel": "Annuler",
    "scheduling.create": "Créer la planification",
    "scheduling.update": "Mettre à jour",
    "scheduling.totalSchedules": "Total planifications",
    "scheduling.active": "Actives",
    "scheduling.paused": "En pause",
    "scheduling.totalRuns": "Total exécutions",
    "scheduling.noSchedules": "Aucune planification",
    "scheduling.noSchedulesDesc": "Créez une planification pour automatiser vos tests de régression.",
    "scheduling.createFirst": "Créer la première planification",
    "scheduling.loading": "Chargement des planifications...",
    "scheduling.selectPlan": "Sélectionner un plan de test...",
    "scheduling.noPlanFound": "Aucun plan de test trouvé. Créez-en un d'abord.",
    "scheduling.maxParallel": "Sessions navigateur en parallèle (max 4)",
    "common.next": "Prochain",
    "common.last": "Dernier",
    "common.never": "Jamais",
    "common.runs": "exécutions",
    "common.overdue": "en retard",
    "common.delete": "Supprimer",
    "common.loading": "Chargement...",
  },
  es: {
    "nav.dashboard": "Panel",
    "nav.testing": "Pruebas",
    "nav.analysis": "Análisis",
    "nav.platform": "Plataforma",
    "nav.testCases": "Casos de prueba",
    "nav.testPlans": "Planes de prueba",
    "nav.testRuns": "Ejecuciones",
    "nav.reports": "Informes",
    "nav.scheduling": "Programación",
    "nav.insights": "Perspectivas",
    "nav.coverage": "Cobertura",
    "nav.organizations": "Organizaciones",
    "profile.account": "Cuenta",
    "profile.settings": "Configuración",
    "profile.organizations": "Organizaciones",
    "profile.usageCredits": "Uso y Créditos",
    "profile.appearance": "Apariencia",
    "profile.language": "Idioma",
    "profile.help": "Ayuda",
    "profile.signOut": "Cerrar sesión",
    "profile.organization": "Organización",
    "appearance.light": "Claro",
    "appearance.dark": "Oscuro",
    "appearance.system": "Sistema",
    "dashboard.title": "Panel",
    "dashboard.subtitle": "Resumen del rendimiento de sus pruebas.",
    "dashboard.projects": "Proyectos",
    "dashboard.testCases": "Casos de prueba",
    "dashboard.successRate": "Tasa de éxito",
    "dashboard.failures": "Fallos",
    "dashboard.executionPlans": "planes de ejecución",
    "dashboard.acrossAllProjects": "Todos los proyectos",
    "dashboard.passed": "pasados",
    "dashboard.failed": "fallados",
    "dashboard.activeRuns": "ejecuciones activas",
    "dashboard.openProjects": "Abrir proyectos",
    "dashboard.teamAccess": "Acceso del equipo",
    "dashboard.executionTrends": "Tendencias de ejecución",
    "dashboard.lastRuns": "Últimas ejecuciones",
    "dashboard.success": "Éxito",
    "dashboard.running": "En curso",
    "dashboard.orgVelocity": "Velocidad de la organización (últimas 30h)",
    "dashboard.recentTestRuns": "Ejecuciones recientes",
    "dashboard.noTestRuns": "Sin ejecuciones aún.",
    "dashboard.noTrendData": "Sin datos de tendencia.",
    "scheduling.title": "Programación TNR",
    "scheduling.subtitle": "Automatice las pruebas de regresión. Configure sesiones paralelas.",
    "scheduling.newSchedule": "Nueva programación",
    "scheduling.editSchedule": "Editar programación",
    "scheduling.scheduleName": "Nombre de la programación",
    "scheduling.testPlan": "Plan de prueba",
    "scheduling.scheduleDate": "Fecha de programación",
    "scheduling.time": "Hora",
    "scheduling.timezone": "Zona horaria",
    "scheduling.parallelSessions": "Sesiones paralelas",
    "scheduling.cancel": "Cancelar",
    "scheduling.create": "Crear programación",
    "scheduling.update": "Actualizar",
    "scheduling.totalSchedules": "Total programaciones",
    "scheduling.active": "Activas",
    "scheduling.paused": "En pausa",
    "scheduling.totalRuns": "Total ejecuciones",
    "scheduling.noSchedules": "Sin programaciones",
    "scheduling.noSchedulesDesc": "Cree una programación para automatizar sus pruebas de regresión.",
    "scheduling.createFirst": "Crear primera programación",
    "scheduling.loading": "Cargando programaciones...",
    "scheduling.selectPlan": "Seleccionar un plan de prueba...",
    "scheduling.noPlanFound": "No se encontraron planes de prueba. Cree uno primero.",
    "scheduling.maxParallel": "Sesiones de navegador en paralelo (máx 4)",
    "common.next": "Siguiente",
    "common.last": "Último",
    "common.never": "Nunca",
    "common.runs": "ejecuciones",
    "common.overdue": "vencido",
    "common.delete": "Eliminar",
    "common.loading": "Cargando...",
  },
};

const LanguageContext = createContext(undefined);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try { return localStorage.getItem("app_language") || "en"; } catch { return "en"; }
  });

  const setLang = useCallback((newLang) => {
    setLangState(newLang);
    try { localStorage.setItem("app_language", newLang); } catch {}
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.en?.[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return { lang: "en", setLang: () => {}, t: (k) => k };
  }
  return context;
}
